### ISSUE TITLE
Print excel sheet

### ISSUE THREAD

**Issue by willauld** [noypi/xlsx#1]
Is there a way to use to to have go print the excel sheet through ole similar to the way it can be done in perl?

**Comment by noypi** [comment]
If it can be done in perl it should be doable in go.
Perhaps try the links below:
https://msdn.microsoft.com/en-us/library/office/ff839804.aspx
https://msdn.microsoft.com/en-us/library/microsoft.office.tools.excel.worksheet.printout(v=vs.120).aspx

**Comment by noypi** [comment]
added PrintOut
https://github.com/noypi/xlsx/commit/ecd8363f72649517fcfcab8052735310177a12f7
https://github.com/noypi/xlsx/commit/34dc1dae54be8852dd6ef545b92159ba2f5dd760

**Comment by willauld** [comment]
Hey, thanks, that is a big help. 

 

I’m planning to move a small tool written in perl to go as a go learning exercise and that was the last thing I had to know I could do before getting started. 

 

Thanks again,

Will
